-- Simplify storage RLS policy to rely on signed URLs for public access
-- The signed URL mechanism in src/lib/storage.ts provides the actual security boundary

-- Drop the unreliable LIKE-based policy
DROP POLICY IF EXISTS "Authenticated users can view approved content files" ON storage.objects;

-- Create simpler policy: only allow contributors to directly access their own files
-- Public access is handled via signed URLs generated by the application
CREATE POLICY "Contributors can access own files"
ON storage.objects
FOR SELECT
USING (
  bucket_id = 'content-files' 
  AND (storage.foldername(name))[1] = auth.uid()::text
);

-- Ensure contributors can still upload to their own folders
DROP POLICY IF EXISTS "Contributors can upload files" ON storage.objects;
CREATE POLICY "Contributors can upload files"
ON storage.objects
FOR INSERT
WITH CHECK (
  bucket_id = 'content-files' 
  AND (storage.foldername(name))[1] = auth.uid()::text
);

-- Allow contributors to update their own files
DROP POLICY IF EXISTS "Contributors can update own files" ON storage.objects;
CREATE POLICY "Contributors can update own files"
ON storage.objects
FOR UPDATE
USING (
  bucket_id = 'content-files' 
  AND (storage.foldername(name))[1] = auth.uid()::text
);

-- Allow contributors to delete their own files
DROP POLICY IF EXISTS "Contributors can delete own files" ON storage.objects;
CREATE POLICY "Contributors can delete own files"
ON storage.objects
FOR DELETE
USING (
  bucket_id = 'content-files' 
  AND (storage.foldername(name))[1] = auth.uid()::text
);